### ISSUE TITLE
general style clean up (spacing, font sizes, etc)

### ISSUE THREAD

**Issue by zebapy** [middlebury/frontend#75]
Ari will be taking a look at basic content styles (headings, font sizes, weights, spacing, etc) so I'm creating this issue to make sure it's tracked and implemented. 

Components
- [x] basic content featured image
- [x] top level page hero (text and large image)
- [x] intro paragraph
- [x] schedule 
- [x] text
- [x] two column text
- [x] image
- [x] video
- [x] faq
- [x] related stories list
- [x] related events list
- [x] homepage featured story
- [x] related stories grid
- [x] related events grid
- [x] related basic content grid 
- [x] sub page list 
- [x] mission selector (fixed in #94)
- [x] event teaser
- [x] story teaser
- [x] event teaser lite
- [x] story teaser lite
- [x] CTAs row on sub pages (open issue #27)
- [x] slideshow
- [x] spotlights
- [x] program panel/career outcomes (open issue #74)
- [x] profile listing + profile heading 

Templates
- [x] top level
- [x] area of focus
- [x] profile detail
- [x] event detail
- [x] event list
- [x] story detail
- [x] story list
- [x] homepage

(will list more as we identify)
